### ISSUE TITLE
drop box listener APItoken

### ISSUE THREAD

**Issue by harem234** [EmpireProject/Empire#1075]
## Empire Version
2.5

## OS Information (Linux flavor, Python version)
kali linux latest
Python latest 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
my port forwarding is correct and i checked after starting listener the service was confirmed from Canyouseeme website but no staging would happen with macro or python script!

both external and private port are the same
Host: is set to external IP
Bindip: is set to private IP

**Comment by DakotaNelson** [comment]
Do you have any information about the actual error occurring or any clues as to why staging isn't happening? Are you getting any messages from Empire?

**Comment by harem234** [comment]
yes there was a series of errors i will provide them as soon as i can.

**Comment by harem234** [comment]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/Desktop/Empire/lib/common/helpers.py", line 900, in __run
    self.__run_backup()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/Desktop/Empire//lib/listeners/dbx.py", line 1082, in start_server
    for match in dbx.files_search(resultsFolder, "*.txt").matches:
  File "/usr/local/lib/python2.7/dist-packages/dropbox/base.py", line 2073, in files_search
    None,
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 272, in request
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 363, in request_json_string_with_retry
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 447, in request_json_string
    timeout=timeout,
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Read timed out. (read timeout=30)

**Comment by harem234** [comment]
after getting an agent it give me this error
and i can get no more agents

**Comment by harem234** [comment]
i found how the error occur
after starting listener on drop box
if internet get disconnected the error occur
the work around is to restart the hole system
why?
i do not know!

**Comment by DakotaNelson** [comment]
Dropbox is killing Empire listeners on their end. The options here are basically either figure out a way to avoid Dropbox's detection of Empire agents, or use another listener.
