### ISSUE TITLE
Empire/Docker : setup_database.py should be run before use

### ISSUE THREAD

**Issue by PierrickV** [EmpireProject/Empire#1080]
## Empire Version

last version on dev branch

## OS Information (Linux flavor, Python version)

Docker

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Has I said here #1033, there is an issue when staring the Docker version of Empire :

(git clone -b dev, docker build -t empire .)

```
~/Empire $ docker run -ti empire      
Traceback (most recent call last):
  File "./empire", line 1418, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire/lib/common/empire.py", line 92, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
  File "/opt/Empire/lib/common/helpers.py", line 554, in get_config
    cur.execute("ALTER TABLE config ADD COLUMN %s BLOB" % (field))
sqlite3.OperationalError: no such table: config
```

The error can be resolv by running setup_database.py

```
~/Empire $ docker run -ti --entrypoint=/bin/bash empire
root@98ce9084ca60:/opt/Empire# python setup/setup_database.py 

 [*] Database setup completed!

[*] Empire shutting down...
root@98ce9084ca60:/opt/Empire# ./empire
[*] Loading stagers from: /opt/Empire//lib/stagers/
[*] Loading modules from: /opt/Empire//lib/modules/
[*] Loading listeners from: /opt/Empire//lib/listeners/
[*] Empire starting up...
```

**Comment by atorralba** [comment]
There's an open pull request (#1065) that fixes just that.
