### ISSUE TITLE
critical notification

### ISSUE THREAD

**Issue by eqhaleel** [EmpireProject/Empire#1098]
the agents fails to call back to the empire server with regards to stagers of macro and oneliners category.hence this is the response with regards to python one liners "Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 14, in <module>
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>"
i hope the developers will look into it. thank you

**Comment by xorrior** [comment]
@eqhaleel Have you done any troubleshooting to eliminate other possibilities for what caused this issue?

**Comment by eqhaleel** [comment]
@xorrior i only tried ./resetting the frame work

**Comment by xorrior** [comment]
@eqhaleel I would recommend some more troubleshooting.
