### ISSUE TITLE
new_allocator

### ISSUE THREAD

**Issue by r3cursive123** [EmpireProject/Empire#1167]
## Empire Version
most recent git clone (6/14/18)

## OS Information (Linux flavor, Python version)
Linux - 3.16.0-4-amd64

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
running setup.sh fails

## Screenshot of error, embedded text output, or Pastebin link to the error

Traceback (most recent call last):
  File "./empire", line 8, in <module>
    from OpenSSL import SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 10, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 18, in <module>
    no_zero_allocator = ffi.new_allocator(should_clear_after_alloc=False)
AttributeError: 'FFI' object has no attribute 'new_allocator'

**Comment by xorrior** [comment]
@r3cursive123 What troubleshooting steps have you taken? Also, please provide the linux distro that you're using.
