### ISSUE TITLE
Server statring for Empire GUI

### ISSUE THREAD

**Issue by 0x4314122** [EmpireProject/Empire#1195]
## OS Information (Linux flavor, Python version)

CentOS Linux release 7.5.1804 (Core) 
Python 2.7.5 (default, Jul 13 2018, 13:06:57) 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Im trying to make server for Empire-GUI but got error 

```
[root Empire]# ./empire --server --shared_password MY_PASSWORD --port 1337
Traceback (most recent call last):
  File "./empire", line 1495, in <module>
    start_collabloration_server(args)
  File "./empire", line 219, in start_collabloration_server
    if args == None:
  File "/usr/lib64/python2.7/argparse.py", line 1158, in __eq__
    return vars(self) == vars(other)
TypeError: vars() argument must have __dict__ attribute
[root Empire]# 
```

**Comment by xorrior** [comment]
@0x4314122 What troubleshooting steps have you tried? Were there any issues during the install?

**Comment by xorrior** [comment]
No activity. Closing
