### ISSUE TITLE
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner

### ISSUE THREAD

**Issue by durilawi** [EmpireProject/Empire#1312]
## Empire Version

[Version] 2.5 
## OS Information (Linux flavor, Python version)
OS:               Microsoft Windows 7 Enterprise
High Integrity:   1
Process Name:     powershell

## Screenshot of error, embedded text output, or Pastebin link to the error

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "./DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./DeathStar.py", line 616, in pwn_the_shit_out_of_everything
    recon(agent_name)
  File "./DeathStar.py", line 510, in recon

Traceback (most recent call last):
  File "./DeathStar.py", line 835, in <module>
    for agent in get_agents()['agents']:
  File "./DeathStar.py", line 118, in get_agents
    return r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by durilawi** [comment]
root@localhost:/home/Empire/DeathStar# ./DeathStar.py --username fuck --password 'Password123!' --debug
[*] Powering up the Death Star
Traceback (most recent call last):
  File "./DeathStar.py", line 813, in <module>
    if not get_listener_by_name():
  File "./DeathStar.py", line 101, in get_listener_by_name
    return r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mr64bit** [comment]
Can you make the REST call manually and make sure it returns the expected listener information?
`https://localhost:1337/api/listeners/DeathStar` (including the admin token of course)
