### ISSUE TITLE
Post Installation Problem

### ISSUE THREAD

**Issue by kazoo123** [EmpireProject/Empire#1323]

**Comment by kazoo123** [comment]
I have been trying to install Empire on Kali 2018 but keeps getting this error.

Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/root/Downloads/Empire/lib/common/empire.py", line 14, in <module>
    from pydispatch import dispatcher
ImportError: No module named pydispatch
root@kali:~/Downloads/Empire/setup# 

I've tried to delete and download the file again and re run it but keeps getting this error. I've also tried to reset it by ./reset.sh but same error..

I've also tried to pip install pydispatch, it looks like it updated but when i tried to lunch empire i keep getting the above above.

Can someone please enlighten me?

Thank you,

**Comment by mr64bit** [comment]
Switch to the `dev` branch and run `setup/install.sh`. If that doesn't fix the problem, can you get me the output of the install script?

**Comment by kazoo123** [comment]
PLEASE HELP ME, AM HAVING SAME ERROR after switching to dev branch

root@kali:~/Downloads/Empire/setup# ./install.sh
http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb
Resolving ftp.us.debian.org (ftp.us.debian.org)... 128.30.2.26, 208.80.154.15, 64.50.236.52, ...
Connecting to ftp.us.debian.org (ftp.us.debian.org)|128.30.2.26|:80... connected

HTTP request sent, awaiting response... 404 Not Found
2019-02-08 07:16:07 ERROR 404: Not Found.

dpkg: error: cannot access archive 'libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb': No such file or directory

Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.5).
default-jdk is already the newest version (2:1.11-71).
g++ is already the newest version (4:8.2.0-2).
libssl1.0-dev is already the newest version (1.0.2q-2).
libxml2-dev is already the newest version (2.9.4+dfsg1-7+b3).
make is already the newest version (4.2.1-1.2).
python-dev is already the newest version (2.7.15-4).
python-m2crypto is already the newest version (0.31.0-2).
python-pip is already the newest version (18.1-4).
swig is already the newest version (3.0.12-2).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-1).
The following packages were automatically installed and are no longer required:
  openjdk-10-jdk openjdk-10-jdk-headless openjdk-10-jre
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1261 not upgraded.
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (19.0.1)
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (1.22)
Requirement already satisfied: requests==2.18.4 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (2.18.4)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (40.2.0)
Requirement already satisfied: iptools in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (0.7.0)
Collecting pydispatcher (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/cd/37/39aca520918ce1935bea9c356bcbb7ed7e52ad4e31bff9b943dfc8e7115b/PyDispatcher-2.0.5.tar.gz
Requirement already satisfied: flask in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 6)) (1.0.2)
Collecting macholib (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/41/f1/6d23e1c79d68e41eb592338d90a33af813f98f2b04458aaf0b86908da2d8/macholib-1.11-py2.py3-none-any.whl
Collecting dropbox (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/67/ad/c4c18d526bcc55b93c00c516f68c3f353fb5f099c459279d3ed18518bd4c/dropbox-9.3.0-py2-none-any.whl
Collecting pyOpenSSL==17.2.0 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/41/bd/751560b317222ba6b6d2e7663a990ac36465aaa026621c6057db130e2faf/pyOpenSSL-17.2.0-py2.py3-none-any.whl
Collecting pyinstaller (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmppruMgs:
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-mlg3kT/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 130, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-mlg3kT/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 112, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-mlg3kT/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 126, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 20, in <module>
      from PyInstaller import __version__ as version, HOMEPATH, PLATFORM
  ImportError: No module named PyInstaller
  
  ----------------------------------------
Command "/usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmppruMgs" failed with error code 1 in /tmp/pip-install-cFfpak/pyinstaller
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
Hit:2 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch InRelease
Get:1 http://ftp.halifax.rwth-aachen.de/kali kali-rolling InRelease [30.5 kB]
Get:3 http://ftp.halifax.rwth-aachen.de/kali kali-rolling/main amd64 Packages [17.1 MB]
Get:4 http://ftp.halifax.rwth-aachen.de/kali kali-rolling/main i386 Packages [17.1 MB]                                   
Fetched 34.2 MB in 3min 3s (187 kB/s)                                                                                    
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version (1.8.0~rc2).
curl is already the newest version (7.63.0-1).
gnupg is already the newest version (2.2.12-1).
The following packages were automatically installed and are no longer required:
  openjdk-10-jdk openjdk-10-jdk-headless openjdk-10-jre
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1261 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   983  100   983    0     0    127      0  0:00:07  0:00:07 --:--:--   247
OK
Hit:2 https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch InRelease             
Hit:1 http://ftp.halifax.rwth-aachen.de/kali kali-rolling InRelease
Reading package lists... Done                                
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 powershell : Depends: libicu57 but it is not installable
E: Unable to correct problems, you have held broken packages.
ls: cannot access '/opt/microsoft/powershell/*/DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY': No such file or directory
xar-1.5.2/
xar-1.5.2/lib/
xar-1.5.2/lib/fbsdattr.c
xar-1.5.2/lib/filetree.h
xar-1.5.2/lib/stat.c
xar-1.5.2/lib/hash.c
xar-1.5.2/lib/ext2.h
xar-1.5.2/lib/darwinattr.h
xar-1.5.2/lib/libxar.la.in.in
xar-1.5.2/lib/archive.c
xar-1.5.2/lib/subdoc.c
xar-1.5.2/lib/script.c
xar-1.5.2/lib/script.h
xar-1.5.2/lib/arcmod.c
xar-1.5.2/lib/arcmod.h
xar-1.5.2/lib/b64.c
xar-1.5.2/lib/subdoc.h
xar-1.5.2/lib/filetree.c
xar-1.5.2/lib/bzxar.c
xar-1.5.2/lib/ext2.c
xar-1.5.2/lib/fbsdattr.h
xar-1.5.2/lib/linuxattr.c
xar-1.5.2/lib/macho.c
xar-1.5.2/lib/ea.h
xar-1.5.2/lib/appledouble.h
xar-1.5.2/lib/darwinattr.c
xar-1.5.2/lib/util.h
xar-1.5.2/lib/util.c
xar-1.5.2/lib/hash.h
xar-1.5.2/lib/zxar.c
xar-1.5.2/lib/data.h
xar-1.5.2/lib/zxar.h
xar-1.5.2/lib/signature.h
xar-1.5.2/lib/bzxar.h
xar-1.5.2/lib/macho.h
xar-1.5.2/lib/signature.c
xar-1.5.2/lib/b64.h
xar-1.5.2/lib/err.c
xar-1.5.2/lib/asprintf.h
xar-1.5.2/lib/stat.h
xar-1.5.2/lib/io.h
xar-1.5.2/lib/linuxattr.h
xar-1.5.2/lib/io.c
xar-1.5.2/lib/ea.c
xar-1.5.2/lib/archive.h
xar-1.5.2/lib/data.c
xar-1.5.2/lib/Makefile.inc.in
xar-1.5.2/cfgoutputs.stamp.in
xar-1.5.2/cfghdrs.stamp.in
xar-1.5.2/config.guess
xar-1.5.2/INSTALL
xar-1.5.2/include/
xar-1.5.2/include/config.h.in
xar-1.5.2/include/xar.h.in
xar-1.5.2/configure
xar-1.5.2/test/
xar-1.5.2/test/checksums
xar-1.5.2/test/functions
xar-1.5.2/test/attr
xar-1.5.2/test/data.xsl
xar-1.5.2/test/buffer.c
xar-1.5.2/test/compression
xar-1.5.2/test/heap1.xsl
xar-1.5.2/test/data
xar-1.5.2/test/heap
xar-1.5.2/test/hardlink
xar-1.5.2/test/validate.c
xar-1.5.2/LICENSE
xar-1.5.2/Makefile.in
xar-1.5.2/src/
xar-1.5.2/src/xar.1
xar-1.5.2/src/xar.c
xar-1.5.2/src/Makefile.inc.in
xar-1.5.2/TODO
xar-1.5.2/configure.ac
xar-1.5.2/xar.spec.in
xar-1.5.2/Mk/
xar-1.5.2/config.sub
xar-1.5.2/install-sh
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for _LARGE_FILES value needed for large files... no
checking how to run the C preprocessor... gcc -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for ld... /usr/bin/ld
checking for ar... /usr/bin/ar
checking for ranlib... /usr/bin/ranlib
checking for autoconf... no
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for egrep... grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking ext2fs/ext2_fs.h usability... no
checking ext2fs/ext2_fs.h presence... no
checking for ext2fs/ext2_fs.h... no
checking sys/statfs.h usability... yes
checking sys/statfs.h presence... yes
checking for sys/statfs.h... yes
checking sys/xattr.h usability... yes
checking sys/xattr.h presence... yes
checking for sys/xattr.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/extattr.h usability... no
checking sys/extattr.h presence... no
checking for sys/extattr.h... no
checking libutil.h usability... no
checking libutil.h presence... no
checking for libutil.h... no
checking for lgetxattr... yes
checking for lsetxattr... yes
checking for getxattr... yes
checking for setxattr... yes
checking for getattrlist... no
checking for setattrlist... no
checking for lchmod... no
checking for lchown... yes
checking for chflags... no
checking for statvfs... yes
checking for statfs... yes
checking for strmode... no
checking for struct statfs.f_fstypename... no
checking for struct statvfs.f_fstypename... no
checking for struct stat.st_flags... no
checking for uid_t... yes
checking size of uid_t... 4
checking for gid_t... yes
checking size of gid_t... 4
checking for ino_t... yes
checking size of ino_t... 8
checking for dev_t... yes
checking size of dev_t... 8
checking for acl_get_file in -lacl... yes
checking for asprintf... yes
checking for xml2-config... /usr/bin/xml2-config
checking for libxml >= 2.6.11... 2.9.4
checking libxml/xmlwriter.h usability... yes
checking libxml/xmlwriter.h presence... yes
checking for libxml/xmlwriter.h... yes
checking openssl/evp.h usability... yes
checking openssl/evp.h presence... yes
checking for openssl/evp.h... yes
checking for OpenSSL_add_all_ciphers in -lcrypto... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for deflate in -lz... yes
checking bzlib.h usability... no
checking bzlib.h presence... no
checking for bzlib.h... no
checking for BZ2_bzCompress in -lbz2... no
configure: creating ./config.status
config.status: creating cfgoutputs.stamp
config.status: creating Makefile
config.status: creating include/xar.h
config.status: creating lib/Makefile.inc
config.status: creating lib/libxar.la.in
config.status: creating src/Makefile.inc
config.status: creating xar.spec
config.status: creating cfghdrs.stamp
config.status: creating include/config.h
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/archive.c -o lib/archive.o
lib/archive.c: In function ‘xar_close’:
lib/archive.c:310:6: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
  int ret, retval = 0;
      ^~~
lib/archive.c: In function ‘xar_unserialize’:
lib/archive.c:1312:12: warning: variable ‘noattr’ set but not used [-Wunused-but-set-variable]
  int type, noattr, ret;
            ^~~~~~
lib/archive.c:1311:33: warning: variable ‘uri’ set but not used [-Wunused-but-set-variable]
  const xmlChar *name, *prefix, *uri;
                                 ^~~
lib/archive.c:1311:24: warning: variable ‘prefix’ set but not used [-Wunused-but-set-variable]
  const xmlChar *name, *prefix, *uri;
                        ^~~~~~
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/arcmod.c -o lib/arcmod.o
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/b64.c -o lib/b64.o
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/bzxar.c -o lib/bzxar.o
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/darwinattr.c -o lib/darwinattr.o
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/data.c -o lib/data.o
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/ea.c -o lib/ea.o
lib/ea.c: In function ‘xar_ea_new’:
lib/ea.c:42:78: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  asprintf((char **)&XAR_ATTR(XAR_PROP(XAR_EA(ret)->prop)->attrs)->value, "%lld", XAR_FILE(f)->nexteaid++);
                                                                           ~~~^
                                                                           %ld
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/err.c -o lib/err.o
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/ext2.c -o lib/ext2.o
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/fbsdattr.c -o lib/fbsdattr.o
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/filetree.c -o lib/filetree.o
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/io.c -o lib/io.o
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/linuxattr.c -o lib/linuxattr.o
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/hash.c -o lib/hash.o
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/signature.c -o lib/signature.o
lib/signature.c: In function ‘xar_signature_serialize’:
lib/signature.c:384:44: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘int32_t’ {aka ‘int’} [-Wformat=]
  xmlTextWriterWriteFormatString(writer, "%ld", (XAR_SIGNATURE(sig)->len));
                                          ~~^   ~~~~~~~~~~~~~~~~~~~~~~~~~
                                          %d
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/stat.c -o lib/stat.o
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/subdoc.c -o lib/subdoc.o
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/util.c -o lib/util.o
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/zxar.c -o lib/zxar.o
lib/zxar.c: In function ‘xar_gzip_toheap_in’:
lib/zxar.c:161:6: warning: variable ‘r’ set but not used [-Wunused-but-set-variable]
  int r;
      ^
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/script.c -o lib/script.o
gcc -Wall -g  -fPIC -DPIC -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/macho.c -o lib/macho.o
gcc -shared -Wl,-soname,libxar.so.1 -o lib/librxar.so.1 lib/archive.o lib/arcmod.o lib/b64.o lib/bzxar.o lib/darwinattr.o lib/data.o lib/ea.o lib/err.o lib/ext2.o lib/fbsdattr.o lib/filetree.o lib/io.o lib/linuxattr.o lib/hash.o lib/signature.o lib/stat.o lib/subdoc.o lib/util.o lib/zxar.o lib/script.o lib/macho.o -lz -lcrypto -lacl  -lxml2
rm -f lib/librxar.so
ln -s librxar.so.1 lib/librxar.so
gcc -shared -Wl,-soname,libxar.so.1 -o lib/libxar.so.1 lib/archive.o lib/arcmod.o lib/b64.o lib/bzxar.o lib/darwinattr.o lib/data.o lib/ea.o lib/err.o lib/ext2.o lib/fbsdattr.o lib/filetree.o lib/io.o lib/linuxattr.o lib/hash.o lib/signature.o lib/stat.o lib/subdoc.o lib/util.o lib/zxar.o lib/script.o lib/macho.o -lz -lcrypto -lacl  -lxml2
rm -f lib/libxar.so
ln -s libxar.so.1 lib/libxar.so
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/archive.c -o lib/archive.static.o
lib/archive.c: In function ‘xar_close’:
lib/archive.c:310:6: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
  int ret, retval = 0;
      ^~~
lib/archive.c: In function ‘xar_unserialize’:
lib/archive.c:1312:12: warning: variable ‘noattr’ set but not used [-Wunused-but-set-variable]
  int type, noattr, ret;
            ^~~~~~
lib/archive.c:1311:33: warning: variable ‘uri’ set but not used [-Wunused-but-set-variable]
  const xmlChar *name, *prefix, *uri;
                                 ^~~
lib/archive.c:1311:24: warning: variable ‘prefix’ set but not used [-Wunused-but-set-variable]
  const xmlChar *name, *prefix, *uri;
                        ^~~~~~
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/arcmod.c -o lib/arcmod.static.o
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/b64.c -o lib/b64.static.o
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/bzxar.c -o lib/bzxar.static.o
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/darwinattr.c -o lib/darwinattr.static.o
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/data.c -o lib/data.static.o
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/ea.c -o lib/ea.static.o
lib/ea.c: In function ‘xar_ea_new’:
lib/ea.c:42:78: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘uint64_t’ {aka ‘long unsigned int’} [-Wformat=]
  asprintf((char **)&XAR_ATTR(XAR_PROP(XAR_EA(ret)->prop)->attrs)->value, "%lld", XAR_FILE(f)->nexteaid++);
                                                                           ~~~^
                                                                           %ld
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/err.c -o lib/err.static.o
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/ext2.c -o lib/ext2.static.o
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/fbsdattr.c -o lib/fbsdattr.static.o
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/filetree.c -o lib/filetree.static.o
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/io.c -o lib/io.static.o
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/linuxattr.c -o lib/linuxattr.static.o
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/hash.c -o lib/hash.static.o
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/signature.c -o lib/signature.static.o
lib/signature.c: In function ‘xar_signature_serialize’:
lib/signature.c:384:44: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘int32_t’ {aka ‘int’} [-Wformat=]
  xmlTextWriterWriteFormatString(writer, "%ld", (XAR_SIGNATURE(sig)->len));
                                          ~~^   ~~~~~~~~~~~~~~~~~~~~~~~~~
                                          %d
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/stat.c -o lib/stat.static.o
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/subdoc.c -o lib/subdoc.static.o
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/util.c -o lib/util.static.o
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/zxar.c -o lib/zxar.static.o
lib/zxar.c: In function ‘xar_gzip_toheap_in’:
lib/zxar.c:161:6: warning: variable ‘r’ set but not used [-Wunused-but-set-variable]
  int r;
      ^
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/script.c -o lib/script.static.o
gcc -Wall -g   -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c lib/macho.c -o lib/macho.static.o
/usr/bin/ar cvr lib/libxar.a lib/archive.static.o lib/arcmod.static.o lib/b64.static.o lib/bzxar.static.o lib/darwinattr.static.o lib/data.static.o lib/ea.static.o lib/err.static.o lib/ext2.static.o lib/fbsdattr.static.o lib/filetree.static.o lib/io.static.o lib/linuxattr.static.o lib/hash.static.o lib/signature.static.o lib/stat.static.o lib/subdoc.static.o lib/util.static.o lib/zxar.static.o lib/script.static.o lib/macho.static.o
a - lib/archive.static.o
a - lib/arcmod.static.o
a - lib/b64.static.o
a - lib/bzxar.static.o
a - lib/darwinattr.static.o
a - lib/data.static.o
a - lib/ea.static.o
a - lib/err.static.o
a - lib/ext2.static.o
a - lib/fbsdattr.static.o
a - lib/filetree.static.o
a - lib/io.static.o
a - lib/linuxattr.static.o
a - lib/hash.static.o
a - lib/signature.static.o
a - lib/stat.static.o
a - lib/subdoc.static.o
a - lib/util.static.o
a - lib/zxar.static.o
a - lib/script.static.o
a - lib/macho.static.o
/usr/bin/ranlib lib/libxar.a 
sed -e s/@LIBXAR_SNAME@/libxar.so.1/ -e s/@LIBXAR_LNAME@/libxar.so/ -e s/@LIBXAR_ANAME@/libxar.a/ < lib/libxar.la.in > lib/libxar.la
gcc -Wall -g  -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c src/xar.c -o src/xar.o
gcc -Wall -g  -o src/xar src/xar.o -Wl,-rpath,/root/Empire/setup/xar-1.5.2/lib -Llib  lib/libxar.a -lz -lcrypto -lacl  -lxml2
gcc -Wall -g  -o src/ixar src/xar.o -Wl,-rpath,/usr/local/lib -Llib  lib/libxar.so.1 -lz -lcrypto -lacl  -lxml2
rm src/xar.o
/usr/bin/install -c -d /usr/local/include/xar
/usr/bin/install -c -m 0644  include/xar.h /usr/local/include/xar
/usr/bin/install -c -d /usr/local/lib
/usr/bin/install -c -m 0755 lib/libxar.so.1 /usr/local/lib
rm -f /usr/local/lib/libxar.so
ln -s libxar.so.1 /usr/local/lib/libxar.so
/usr/bin/install -c -m 0644 lib/libxar.a /usr/local/lib
/usr/bin/install -c -m 0644 lib/libxar.la /usr/local/lib
gcc -Wall -g  -Iinclude -Iinclude -D_GNU_SOURCE -I/usr/include/libxml2 -c src/xar.c -o src/xar.o
gcc -Wall -g  -o src/ixar src/xar.o -Wl,-rpath,/usr/local/lib -Llib  lib/libxar.so.1 -lz -lcrypto -lacl  -lxml2
/usr/bin/install -c -d /usr/local/bin
/usr/bin/install -c -m 0755 src/ixar /usr/local/bin/xar
/usr/bin/install -c -d /usr/local/man/man1
/usr/bin/install -c -m 0644 src/xar.1 /usr/local/man/man1
Cloning into 'bomutils'...
remote: Enumerating objects: 246, done.
remote: Total 246 (delta 0), reused 0 (delta 0), pack-reused 246
Receiving objects: 100% (246/246), 1.20 MiB | 324.00 KiB/s, done.
Resolving deltas: 100% (126/126), done.
g++ -o build/obj/mkbom.o -c -O2 -g0 -s -Wall  src/mkbom.cpp
g++ -o build/obj/printnode.o -c -O2 -g0 -s -Wall  src/printnode.cpp
g++ -o build/obj/crc32.o -c -O2 -g0 -s -Wall  src/crc32.cpp
g++ -o build/bin/mkbom  build/obj/mkbom.o build/obj/printnode.o build/obj/crc32.o 
g++ -o build/obj/dumpbom.o -c -O2 -g0 -s -Wall  src/dumpbom.cpp
g++ -o build/bin/dumpbom  build/obj/dumpbom.o build/obj/printnode.o build/obj/crc32.o 
g++ -o build/obj/lsbom.o -c -O2 -g0 -s -Wall  src/lsbom.cpp
g++ -o build/bin/lsbom  build/obj/lsbom.o build/obj/printnode.o build/obj/crc32.o 
g++ -o build/obj/ls4mkbom.o -c -O2 -g0 -s -Wall  src/ls4mkbom.cpp
g++ -o build/bin/ls4mkbom  build/obj/ls4mkbom.o build/obj/printnode.o build/obj/crc32.o 
gzip -c man/mkbom.1 > build/man/mkbom.1.gz
gzip -c man/dumpbom.1 > build/man/dumpbom.1.gz
gzip -c man/lsbom.1 > build/man/lsbom.1.gz
gzip -c man/ls4mkbom.1 > build/man/ls4mkbom.1.gz
install -d /usr/bin
install -d /usr/share/man/man1
install -m 0755 build/bin/mkbom build/bin/dumpbom build/bin/lsbom build/bin/ls4mkbom /usr/bin
install -m 0644 build/man/mkbom.1.gz build/man/dumpbom.1.gz build/man/lsbom.1.gz build/man/ls4mkbom.1.gz /usr/share/man/man1
install -d /usr/bin
install -d /usr/share/man/man1
install -m 0755 build/bin/mkbom build/bin/dumpbom build/bin/lsbom build/bin/ls4mkbom /usr/bin
install -m 0644 build/man/mkbom.1.gz build/man/dumpbom.1.gz build/man/lsbom.1.gz build/man/ls4mkbom.1.gz /usr/share/man/man1

 [>] Enter server negotiation password, enter for random generation: 

 [*] Database setup completed!


 [*] Certificate written to ../data/empire-chain.pem
 [*] Private key written to ../data/empire-priv.key


 [*] Setup complete!

root@kali:~/Empire/setup# 
==============================================

root@kali:~/Empire# ./empire
Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/root/Empire/lib/common/empire.py", line 14, in <module>
    from pydispatch import dispatcher
ImportError: No module named pydispatch

root@kali:~/Empire# pip install pydispatch

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: pydispatch in /usr/local/lib/python2.7/dist-packages (1.1.0)
Requirement already satisfied: six>=1.5.2 in /usr/lib/python2.7/dist-packages (from pydispatch) (1.11.0)
Requirement already satisfied: colorama>=0.2.7 in /usr/lib/python2.7/dist-packages (from pydispatch) (0.3.7)

root@kali:~/Empire# ./empire

Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/root/Empire/lib/common/empire.py", line 14, in <module>
    from pydispatch import dispatcher
ImportError: No module named pydispatch

root@kali:~/Empire#

**Comment by mr64bit** [comment]
Is your dev branch up to date with what's on Github? Looks like it's still trying to pull the old version of libssl.
