### ISSUE TITLE
issue with install

### ISSUE THREAD

**Issue by isHaacK** [EmpireProject/Empire#1324]
## OS Information (Linux flavor, Python version)
Kali linux, Python 2.7.15

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

setup/install.sh is not working because pyinstaller is giving an error. Also i had to change libssl1.0.0_1.0.1t-1+deb8u7_amd64.deb to deb8u8.

## Screenshot of error, embedded text output, or Pastebin link to the error

pip install pyinstaller

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pyinstaller
  Using cached https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpP1E683:
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-nJ9qdr/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 130, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-nJ9qdr/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 112, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-nJ9qdr/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 126, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 20, in <module>
      from PyInstaller import __version__ as version, HOMEPATH, PLATFORM
  ImportError: No module named PyInstaller
  
  ----------------------------------------
Command "/usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpP1E683" failed with error code 1 in /tmp/pip-install-gw_Wxl/pyinstaller

**Comment by mr64bit** [comment]
There's several issues with the install script that have been fixed in `dev`. That should solve both your issues here. You'll have to roll pip back to 18.1 manually before running the install script.

**Comment by isHaacK** [comment]
that worked for me thanks
