### ISSUE TITLE
Error post installation

### ISSUE THREAD

**Issue by tXambe** [EmpireProject/Empire#1342]
## Empire Version
 2.3 

## OS Information (Linux flavor, Python version)
Debian 9.8

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

After instalation I have this error:
 Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/opt/Empire-mod-Hackplayers/lib/common/empire.py", line 31, in <module>
    import agents
  File "/opt/Empire-mod-Hackplayers/lib/common/agents.py", line 68, in <module>
    import encryption
  File "/opt/Empire-mod-Hackplayers/lib/common/encryption.py", line 26, in <module>
    import M2Crypto
ImportError: No module named M2Crypto

**Comment by Depharms** [comment]
For me:
- sudo apt-get install python-dev
- sudo apt-get python-m2crypto
