### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by MasterGun2006** [EmpireProject/Empire#1370]
I can't run Empire. Everytime I am trying to run it it gives this error. 
Traceback (most recent call last):
  File "./empire", line 1422, in <module>
    main = empire.MainMenu(args=args)
  File "/root/Документы/Empire-master/lib/common/empire.py", line 92, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable

**Comment by BC-SECURITY** [comment]
https://github.com/EmpireProject/Empire/issues/1330
https://github.com/EmpireProject/Empire/issues/1278
https://github.com/EmpireProject/Empire/issues/1264
https://github.com/EmpireProject/Empire/issues/1310
