### ISSUE TITLE
download - dosn't accept national characters in filename

### ISSUE THREAD

**Issue by randomek** [EmpireProject/Empire#401]
## Empire Version
1.0

## OS Information (Linux flavor, Python version)
Ubuntu Server 16, Python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
It should download file "xxxxxxxxx-hasło.doc" with "ł" letter inside.

## Screenshot of error, embedded text output, or Pastebin link to the error

download xxxxxxxxx-hasło.doc

Exception happened during processing of request from ('111.111.111.111', 12345)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/root/Empire-master/lib/common/http.py", line 100, in do_GET
    (code, responsedata) = self.server.agents.process_get(self.server.server_port, clientIP, sessionID, resource)
  File "/root/Empire-master/lib/common/agents.py", line 1174, in process_get
    all_task_packets += packets.build_task_packet(task_name, task_data)
  File "/root/Empire-master/lib/common/packets.py", line 106, in build_task_packet
    return taskID + counter + length + data.decode('utf-8').encode('utf-8',errors='ignore')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0142' in position 30: ordinal not in range(128)

**Comment by xorrior** [comment]
We'll take a look and see if we can add support for unicode characters but it won't be something we have an immediate fix for.

**Comment by xorrior** [comment]
Fixed #489
