### ISSUE TITLE
Empire error after setup ("/pentest/powershell/empire-ps/lib/common/empire.py", line 22, in )

### ISSUE THREAD

**Issue by alienwaresoldier** [EmpireProject/Empire#454]
I try to install Empire but I keep on gettin this error after the setup is done.

> └──╼ #cd /pentest/
┌─[root@parrot]─[/pentest]
└──╼ #cd powershell/
┌─[root@parrot]─[/pentest/powershell]
└──╼ #ls
babadook    empire-ps       invoke-obfuscation  nps        powersploit
bloodhound  generate-macro  nishang             powersccm  ps-payload-excel
┌─[root@parrot]─[/pentest/powershell]
└──╼ #cd empire-ps
┌─[root@parrot]─[/pentest/powershell/empire-ps]
└──╼ #ls
changelog  data  empire  lib  LICENSE  README.md  setup
┌─[root@parrot]─[/pentest/powershell/empire-ps]
└──╼ #cd /root
┌─[root@parrot]─[~]
└──╼ #empire
empire
Traceback (most recent call last):
  File "./empire", line 10, in <module>
    from lib.common import empire
  File "/pentest/powershell/empire-ps/lib/common/empire.py", line 22, in <module>
    from pydispatch import dispatcher
ImportError: No module named pydispatch
┌─[✗]─[root@parrot]─[~]
└──╼ #

>  #cd Empire
┌─[root@parrot]─[~/Empire]
└──╼ #ls
changelog  data  empire  lib  LICENSE  README.md  setup
┌─[root@parrot]─[~/Empire]
└──╼ #ls
changelog  data  empire  lib  LICENSE  README.md  setup
┌─[root@parrot]─[~/Empire]
└──╼ #empire
empire
Traceback (most recent call last):
  File "./empire", line 10, in <module>
    from lib.common import empire
  File "/pentest/powershell/empire-ps/lib/common/empire.py", line 22, in <module>
    from pydispatch import dispatcher
ImportError: No module named pydispatch
┌─[✗]─[root@parrot]─[~/Empire]
└──╼ #cd setup
┌─[root@parrot]─[~/Empire/setup]
└──╼ #ls
cert.sh  install.sh  reset.sh  setup_database.py
┌─[root@parrot]─[~/Empire/setup]
└──╼ # ./setup/reset.sh
bash: ./setup/reset.sh: No such file or directory
┌─[✗]─[root@parrot]─[~/Empire/setup]
└──╼ # ./setup/install.sh
bash: ./setup/install.sh: No such file or directory
┌─[✗]─[root@parrot]─[~/Empire/setup]
└──╼ #./setup/setup_database.py
bash: ./setup/setup_database.py: No such file or directory
┌─[✗]─[root@parrot]─[~/Empire/setup]
└──╼ #cd setup_database.py
bash: cd: setup_database.py: Not a directory
┌─[✗]─[root@parrot]─[~/Empire/setup]
└──╼ #ls
cert.sh  install.sh  reset.sh  setup_database.py
┌─[root@parrot]─[~/Empire/setup]
└──╼ #./install.sh
]Unknown distro - Debian/Ubuntu Fallback
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl-dev is already the newest version (1.1.0c-2).
python-dev is already the newest version (2.7.13-2).
python-m2crypto is already the newest version (0.24.0-1.1).
python-pip is already the newest version (9.0.1-2).
swig is already the newest version (3.0.10-1.1).
0 upgraded, 0 newly installed, 0 to remove and 36 not upgraded.
Requirement already satisfied: pycrypto in /usr/lib/python2.7/dist-packages
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 487, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 414, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1025, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(str(no_marker))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 552, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 426, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 844, in resolve
    env = Environment(self.entries)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1051, in __init__
    self.scan(search_path)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1081, in scan
    self.add(dist)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1101, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2452, in hashcmp
    self.parsed_version,
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2499, in parsed_version
    self._parsed_version = parse_version(self.version)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 201, in parse_version
    return SetuptoolsVersion(v)
  File "/usr/local/lib/python2.7/dist-packages/packaging/version.py", line 202, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
InvalidVersion: Invalid version: '7.40SVN'
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 487, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 414, in _check_skip_installed
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1025, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(str(no_marker))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 552, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 426, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 844, in resolve
    env = Environment(self.entries)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1051, in __init__
    self.scan(search_path)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1081, in scan
    self.add(dist)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1101, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2452, in hashcmp
    self.parsed_version,
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2499, in parsed_version
    self._parsed_version = parse_version(self.version)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 201, in parse_version
    return SetuptoolsVersion(v)
  File "/usr/local/lib/python2.7/dist-packages/packaging/version.py", line 202, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
InvalidVersion: Invalid version: '7.40SVN'
Requirement already satisfied: flask in /usr/lib/python2.7/dist-packages
Requirement already satisfied: pyOpenSSL in /usr/lib/python2.7/dist-packages

 [>] Enter server negotiation password, enter for random generation: 
Traceback (most recent call last):
  File "./setup_database.py", line 128, in <module>
    )''')
sqlite3.OperationalError: table config already exists

 [*] Certificate written to ../data/empire.pem

 [*] Setup complete!

┌─[root@parrot]─[~/Empire/setup]
└──╼ #ls
cert.sh  install.sh  reset.sh  setup_database.py
┌─[root@parrot]─[~/Empire/setup]
└──╼ #./reset.sh

 [>] Enter server negotiation password, enter for random generation: 

 [*] Database setup completed!

Traceback (most recent call last):
  File "./empire", line 10, in <module>
    from lib.common import empire
  File "/root/Empire/lib/common/empire.py", line 22, in <module>
    from pydispatch import dispatcher
ImportError: No module named pydispatch
┌─[✗]─[root@parrot]─[~/Empire/setup]
└──╼ #ls
cert.sh  install.sh  reset.sh  setup_database.py
┌─[root@parrot]─[~/Empire/setup]
└──╼ #./setup_database.py

 [>] Enter server negotiation password, enter for random generation: 
Traceback (most recent call last):
  File "./setup_database.py", line 128, in <module>
    )''')
sqlite3.OperationalError: table config already exists
┌─[✗]─[root@parrot]─[~/Empire/setup]
└──╼ #

**Comment by alienwaresoldier** [comment]
*SOLVED and Empire is working like a charme.
Simple followed this link: https://github.com/EmpireProject/Empire/issues/429
