### ISSUE TITLE
'ascii' codec can't encode characters in position 3-6: ordinal not in range(128)

### ISSUE THREAD

**Issue by n0n0n0n0** [EmpireProject/Empire#542]
## Empire Version
latest

## OS Information (Linux flavor, Python version)
debian 7

when i'm trying to cd or ls folder with russian name(for example)

> Фото

it shows me 
```
File "/root/Empire-master/lib/common/packets.py", line 167, in build_task_packet
    return taskType + totalPacket + packetNum + resultID + length + data.decode('utf-8').encode('utf-8',errors='ignore')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-6: ordinal not in range(128)
```
if i set default language for python to utf-8 in empire file it will show:
```
invalid packet: <here huge number>
```
seems packet just gets broken

i've tried to install locales/etc from google, nothing help

**Comment by xorrior** [comment]
This has been fix per #589

**Comment by n0n0n0n0** [comment]
still have problem while trying cd/etc to folder with russian name

**Comment by n0n0n0n0** [comment]
Problem still exists, used latest version from dev
Now even when client trying to connect:
```
[2017-11-05 15:32:08,106] ERROR in app: Exception on /admin/get.php [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/Empire//lib/listeners/http.py", line 891, in handle_get
    dispatcher.send("[!] Error from agents.handle_agent_data() for %s from %s: %s" % (request_uri, clientIP, results), sender='listeners/http')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbe in position 18: ordinal not in range(128)
```

**Comment by n0n0n0n0** [comment]
btw according to b3b80cb6a8a3430205cd80c532b5edb4aee16508
it anyway will not fix them problem when we try cd/etc to folder with russian name, or download file, etc

**Comment by DakotaNelson** [comment]
This has been reopened by #1011.

**Comment by n0n0n0n0** [comment]
Easy to reproduce, create a folder with russian name and try to cd there, or try to download file with russian name, still not working.

**Comment by DakotaNelson** [comment]
This is probably going to be a giant dev pain... basically we have to go through everywhere and make sure there are correct `encode` and `decode` calls and that nothing assumes ascii. Doable but ugh.

@n0n0n0n0 if you have some spare cycles you can go to the line number indicated in the stack trace and try a `variable_causing_problems.encode('utf-8')`. If you track down all the places that variable is used and do proper `encode`/`decode` calls that will almost certainly fix your problem.

**Comment by LIZySARA** [comment]
Hi,

What is the solution to this problem?

![screenshot_1](https://user-images.githubusercontent.com/22563762/37398465-8a4021a0-2776-11e8-9ad0-568f162956e6.png)

**Comment by xorrior** [comment]
@LIZySARA we don't have a solution currently. If this is urgent, you can try @DakotaNelson's suggestion.

**Comment by n0n0n0n0** [comment]
@DakotaNelson with your suggestion i see only questions rather than normal words.

**Comment by LIZySARA** [comment]
@xorrior  thx

**Comment by winnie22** [comment]
Hi, all. You can try add the following code to ./empire after import section:
`
reload(sys)
sys.setdefaultencoding('UTF8')
`

This prevent mentioned exceptions, I think, and I'm event able to download file as mention later. But there is still something wrong. When you do cd command i got invalid type error:
`
(Empire: VR7HGU8F) > cd řěšč
(Empire: VR7HGU8F) > [!] Received error response from VR7HGU8F
[*] Agent VR7HGU8F returned results.
Path                   
----                   
C:\Users\winnie\Desktop
invalid type: 41413
`
You can do cd or download using question marks as follows:
`
(Empire: VR7HGU8F) > cd ????
[*] Tasked VR7HGU8F to run TASK_SHELL
[*] Agent VR7HGU8F tasked with task ID 23
(Empire: VR7HGU8F) > [*] Agent VR7HGU8F returned results.
Path                        
----                        
C:\Users\winnie\Desktop\řěšč
[*] Valid results returned by 192.168.1.10
pwd
[*] Tasked VR7HGU8F to run TASK_SHELL
[*] Agent VR7HGU8F tasked with task ID 24
(Empire: VR7HGU8F) > [*] Agent VR7HGU8F returned results.
Path                        
----                        
C:\Users\winnie\Desktop\řěšč
[*] Valid results returned by 192.168.1.10

(Empire: VR7HGU8F) > download ???????.txt
[*] Tasked VR7HGU8F to run TASK_DOWNLOAD
[*] Agent VR7HGU8F tasked with task ID 27
(Empire: VR7HGU8F) > [+] Part of file čžýýážř.txt from VR7HGU8F saved
[*] Agent VR7HGU8F returned results.
[*] Valid results returned by 192.168.1.10
[*] Agent VR7HGU8F returned results.
[*] File download of C:\Users\winnie\Desktop\čžýýážř.txt completed
[*] Valid results returned by 192.168.1.10
`

But cant find the main cause. Tried to play with PS agent encoding, but no luck.

**Comment by LIZySARA** [comment]
@ winnie22

Hi, all. You can try add the following code to ./empire after import section:
reload(sys)
sys.setdefaultencoding('UTF8') 

Hi, can you make the change and then capture us?
thx

**Comment by xorrior** [comment]
@n0n0n0n0 The partial patch from #1083 has been applied to the dev and master branch. We'll keep this open until we have a complete solution.

**Comment by winnie22** [comment]
Hi all, good news! #1093 should fix this issue. mkdir/cd/pwd/download everythink works for me.

**Comment by winnie22** [comment]
Hi, everyone! I just tested dev branch with merged fix and everything works for me. Can anyone verify this fix, so we can close this issue? Thanks

**Comment by xorrior** [comment]
@winnie22 I'll take a look at it

**Comment by xorrior** [comment]
@winnie22 it looks like cd, pwd, etc work just fine. Download still has issues.

![image](https://user-images.githubusercontent.com/9156069/39676580-3c597b0a-513b-11e8-92c4-53a3fba58b53.png)

![image](https://user-images.githubusercontent.com/9156069/39676583-40b6e16a-513b-11e8-8563-a93f1c994a78.png)

**Comment by winnie22** [comment]
Hi, @xorrior thanks for testing! According to your file listing, size of the file is 0, which doesn't download anything (I hit this "feature" couple off times :)). Could you please validate download with file with size larger than 0. Thanks!
