### ISSUE TITLE
urlib3 timeout.py Problem

### ISSUE THREAD

**Issue by 8aplus** [EmpireProject/Empire#604]
## Empire Version
2.0

## OS Information (Linux flavor, Python version)
Kali Rolling 2017
urllib==1.21.1
urllib3==1.21.1
Python 2.7.13
Python 3.5.3+ 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

I want to execute a Stager. ApiKey is set but when execute I get the following message. 
Someone knows a solution for this problem?

## Screenshot of error, embedded text output, or Pastebin link to the error

```
(Empire: listeners/dbx) > execute
[*] Starting listener 'dropbox'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/git/Empire/lib/common/helpers.py", line 792, in __run
    self.__run_backup()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/git/Empire//lib/listeners/dbx.py", line 751, in start_server
    dbx.users_get_current_account()
  File "/usr/local/lib/python2.7/dist-packages/dropbox/base.py", line 3277, in users_get_current_account
    None,
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 234, in request
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 325, in request_json_string_with_retry
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 409, in request_json_string
    timeout=timeout,
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 587, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 302, in _get_timeout
    return Timeout.from_float(timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=30, read=30, total=None), but it must be an int, float or None.

```

**Comment by chowdaryd** [comment]
@8aplus this can happen if you don't have the latest ```python-requests``` module. Can you confirm if the bug remains after you update the ```python-requests``` module. Please run ```pip install -U requests```

**Comment by 8aplus** [comment]
Great it works. Thx a lot!

**Comment by jihadLkmaty218** [comment]
Be sure to issue Python and with update::)
