### ISSUE TITLE
Dropbox listener fails. Requests library issue

### ISSUE THREAD

**Issue by pseudoeuro** [EmpireProject/Empire#624]
Empire version used is 2.0 on Kali Linux rolling, if you try to execute dropbox listener it will drop this error:

```
[*] Starting listener 'dropbox'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/Empire/lib/common/helpers.py", line 792, in __run
    self.__run_backup()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/Empire//lib/listeners/dbx.py", line 751, in start_server
    dbx.users_get_current_account()
  File "/usr/local/lib/python2.7/dist-packages/dropbox/base.py", line 3277, in users_get_current_account
    None,
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 234, in request
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 325, in request_json_string_with_retry
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 409, in request_json_string
    timeout=timeout,
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 581, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 307, in _get_timeout
    return Timeout.from_float(timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 157, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 97, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 130, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=30, read=30, total=None), but it must be an int, float or None.
 
[!] Listener failed to start!

```
Apparently the python requests library is to blame for it and needs to be updated to the latest version. 

`pip install requests --upgrade` will fix the issue. 

Might be a good idea for empire to check if requests is updated while installing?

**Comment by benichmt1** [comment]
I also got this issue in ubuntu 14.04

**Comment by xorrior** [comment]
@benichmt1 what version of pip did you use to upgrade?

**Comment by xorrior** [comment]
@pseudoeuro I'll add this to the install script.

**Comment by benichmt1** [comment]
I was trying 
`pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)`

**Comment by xorrior** [comment]
@pseudoeuro I updated the install script to remedy this.
