### ISSUE TITLE
Unable to list listeners or view stagers via the CLI

### ISSUE THREAD

**Issue by Jamie-** [EmpireProject/Empire#634]
## Empire Version
```
# ./empire -v
2.0
```

## OS Information (Linux flavor, Python version)
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
# uname -a
Linux ubuntu 4.10.0-30-generic #34-Ubuntu SMP Mon Jul 31 19:38:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I setup a listener in empire as follows:
```
(Empire) > listeners
[!] No listeners currently active 
(Empire: listeners) > uselistener http
(Empire: listeners/http) > set Port 1234
(Empire: listeners/http) > execute
[*] Starting listener 'http'
[+] Listener successfully started!
(Empire: listeners/http) > exit

[>] Exit? [y/N] y

[!] Shutting down...
[!] Killing listener 'http'
```

Then tried to view the listener using the CLI (in order to later generate a stager) with `./empire -l` and got the following error:
```
# ./empire -l
Traceback (most recent call last):
  File "./empire", line 1294, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/empire/lib/common/empire.py", line 89, in __init__
    self.handle_args()
  File "/opt/empire/lib/common/empire.py", line 143, in handle_args
    messages.display_active_listeners(self.listeners.activeListeners)
AttributeError: MainMenu instance has no attribute 'listeners'
```
The listener I created was named as default ('http') and I also tried `./empire -l http` to get an almost identical error. Shown here for completeness:
```
# ./empire -l http
Traceback (most recent call last):
  File "./empire", line 1294, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/empire/lib/common/empire.py", line 89, in __init__
    self.handle_args()
  File "/opt/empire/lib/common/empire.py", line 145, in handle_args
    activeListeners = self.listeners.activeListeners
AttributeError: MainMenu instance has no attribute 'listeners'
```
I've also tried having an empire instance running in another terminal while running these commands and hit the same error.

Same happens with stagers:
```
# ./empire -s

Stagers:

  Name             Description
  ----             -----------
Traceback (most recent call last):
  File "./empire", line 1294, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/empire/lib/common/empire.py", line 89, in __init__
    self.handle_args()
  File "/opt/empire/lib/common/empire.py", line 160, in handle_args
    for stagerName, stager in self.stagers.stagers.iteritems():
AttributeError: MainMenu instance has no attribute 'stagers'
```

**Comment by rvrsh3ll** [comment]
thank you for the notification of this bug. A fix has been pushed to the DEV branch.
