### ISSUE TITLE
Bad check for ./data/empire.pem

### ISSUE THREAD

**Issue by Chiggins** [EmpireProject/Empire#700]
## Empire Version
2.1 (dfb049ed48165eff2a8c1fe41941d0fbfa42df31)

## OS Information (Linux flavor, Python version)
Kali, Python 2.7.13

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Ran with `./empire --rest --username user --password pass --restport 1337`
Errors followed immediately, shown below.

## Screenshot of error, embedded text output, or Pastebin link to the error
```
 * Starting Empire RESTful API on port: 1337        
 * RESTful API token: ekhxc52kn2it8gburkes1v74gozax1oou2g4l2pn                                           
[!] Error: cannot find certificate ./data/empire.pem                                                     

 * Starting Empire RESTful API on port: 1337        
 * RESTful API token: ndrfudv0o2mn67bofylmoloxeux87zgvbo9arcan                                           
[!] Error: cannot find certificate ./data/empire.pem                                                     

 * Starting Empire RESTful API on port: 1337        
 * RESTful API token: y54626bec8o7zc2fd1um9h2hsrb5p14kj2aa6cvd                                           
[!] Error: cannot find certificate ./data/empire.pem                                                     

 * Starting Empire RESTful API on port: 1337        
 * RESTful API token: 28dbnpoix25nbxv95cokh4dzxec236y5o0ao8vac                                           
[!] Error: cannot find certificate ./data/empire.pem                                                     

 * Starting Empire RESTful API on port: 1337        
 * RESTful API token: 0a7ewh3rain8uzdl494mzfqz9d82rb4gfv16g5g0                                           
[!] Error: cannot find certificate ./data/empire.pem                                                     

 * Starting Empire RESTful API on port: 1337        
 * RESTful API token: nmplsw9d3ujqemq6czbiw740ssh5e4qz6iuh2lm2                                           
[!] Error: cannot find certificate ./data/empire.pem                                                     

 * Starting Empire RESTful API on port: 1337        
 * RESTful API token: v639nub6os85mk1xaddbo63ji0gzrsxffm14gcd7                                           
[!] Error: cannot find certificate ./data/empire.pem            
```

## Any additional information
Already have a fix, will PR it in a moment.

**Comment by SadProcessor** [comment]
Have same error (looping) when starting in --rest
Tried starting with --headless but also fails
following error on ctrl-c
```
 * Starting Empire RESTful API on port: 1337
 * RESTful API token: zatcwhsm1xg8mevbux5uekebxpyrglyagh1wgxub

^CTraceback (most recent call last):
  File "./empire", line 1280, in <module>
    start_restful_api(empireMenu=main, suppress=True, username=args.username, password=args.password, port=args.restport)
  File "./empire", line 370, in start_restful_api
    @app.route('/api/modules/<path:module_name>', methods=['GET'])
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1080, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1046, in add_url_rule
    self.url_map.add(rule)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/routing.py", line 1197, in add
    rule.bind(self)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/routing.py", line 681, in bind
    self.compile()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/routing.py", line 731, in compile
    _build_regex(self.is_leaf and self.rule or self.rule.rstrip('/'))
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/routing.py", line 713, in _build_regex
    self._weights.append((0, -len(part)))
KeyboardInterrupt
root@DeadMouse:/opt/Empire# 
```

**Comment by xorrior** [comment]
This is fixed in at least dev. Thanks
