### ISSUE TITLE
TypeError: obfuscate() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by DaleMitchell** [EmpireProject/Empire#769]
## Empire Version - 2.2

When obfuscate is set True from the main menu and an http agent connects:

```
(Empire: listeners) > [2017-10-20 19:23:37,782] ERROR in app: Exception on /admin/get.php [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "empire//lib/listeners/http.py", line 877, in handle_get
    stage = self.generate_stager(language=language, listenerOptions=listenerOptions, obfuscate=self.mainMenu.obfuscate, obfuscationCommand=self.mainMenu.obfuscateCommand)
  File "empire//lib/listeners/http.py", line 497, in generate_stager
    randomizedStager = helpers.obfuscate(randomizedStager, obfuscationCommand=obfuscationCommand)
TypeError: obfuscate() takes exactly 3 arguments (2 given)
```

**Comment by DaleMitchell** [comment]
Someone was sloppy:
https://github.com/EmpireProject/Empire/commit/b944a188d20a541f31821f89634a497c59b06013#diff-0f0ac39cf0dcc3046cc1bd57f61f58ac

**Comment by xorrior** [comment]
@DaleMitchell It'll be fixed shortly. Thanks.

**Comment by xorrior** [comment]
Fixed in dev.

**Comment by DaleMitchell** [comment]
This is also a problem in most of the modules. For example: https://github.com/EmpireProject/Empire/blob/0e94876a5609c30c29cb692fd757643dd94a813a/lib/modules/powershell/management/logoff.py#L65

**Comment by xorrior** [comment]
on it
