### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by sitanshuforever** [EmpireProject/Empire#782]
I am running kubuntu. plasma 5.

just tried "sudo ./install.sh". It finished. Then i started empire.. "./empire".

![image](https://user-images.githubusercontent.com/2941024/32095192-ff071124-bb1f-11e7-9b0d-e4dcec9cb4f6.png)

**Comment by xorrior** [comment]
@sitanshuforever it finished but were there any errors in the output? Specifically with setting up the database?

**Comment by DakotaNelson** [comment]
I was also getting this:

```
 [>] Enter server negotiation password, enter for random generation: 
Traceback (most recent call last):
  File "./setup_database.py", line 130, in <module>
    )''')
sqlite3.OperationalError: table "agents" already exists

 [*] Certificate written to ../data/empire-chain.pem
 [*] Private key written to ../data/empire-priv.key


 [*] Setup complete!

[dnelson@sulaco Empire]$ ./empire --headless
Traceback (most recent call last):
  File "./empire", line 1355, in <module>
    main = empire.MainMenu(args=args)
  File "/home/dnelson/projects/Empire/lib/common/empire.py", line 76, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable
```

Running `rm ./data/empire.db` and `./setup/reset.sh`meant I got this instead:

```
 * Starting Empire RESTful API on port: 1337
Traceback (most recent call last):
  File "./empire", line 1358, in <module>
    start_restful_api(empireMenu=main, suppress=True, username=args.username, password=args.password, port=args.restport)
  File "./empire", line 188, in start_restful_api
    apiToken = refresh_api_token(conn)
  File "./empire", line 66, in refresh_api_token
    execute_db_query(conn, "UPDATE config SET api_current_token=?", [apiToken])
  File "./empire", line 49, in execute_db_query
    cur.execute(query, args)
sqlite3.OperationalError: attempt to write a readonly database
```

Which makes sense given:

```
[dnelson@sulaco Empire]$ ls -l data/
total 72
drwxrwxr-x.  3 dnelson dnelson  4096 Oct 21 20:38 agent
-rw-r--r--.  1 root    root     1074 Oct 29 11:12 empire-chain.pem
-rw-r--r--.  1 root    root    40960 Oct 29 11:15 empire.db
-rw-r--r--.  1 root    root     1704 Oct 29 11:12 empire-priv.key
drwxrwxr-x.  7 dnelson dnelson  4096 Oct 21 20:38 misc
drwxrwxr-x. 16 dnelson dnelson  4096 Oct 21 19:00 module_source
drwxrwxr-x. 15 dnelson dnelson  4096 Oct 21 19:00 obfuscated_module_source
drwxrwxr-x.  2 dnelson dnelson  4096 Oct 21 19:00 profiles
[dnelson@sulaco Empire]$ 
```

So running `sudo chown dnelson:dnelson data/empire.db` fixed it.

**Comment by xorrior** [comment]
@sitanshuforever If you run install.sh with sudo, but then run empire without sudo you won't be able to write to the database created by the setup script.
