### ISSUE TITLE
centos install error

### ISSUE THREAD

**Issue by net2net** [EmpireProject/Empire#832]
## Empire Version
newsest version
 
## OS Information (Linux flavor, Python version)
centos 6.4 python2.6

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
[root@MyCloudServer Empire]# ./empire
[*] Loading stagers from: /opt/Empire//lib/stagers/
[*] Loading modules from: /opt/Empire//lib/modules/
Traceback (most recent call last):
  File "./empire", line 1365, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire/lib/common/empire.py", line 94, in __init__
    self.modules = modules.Modules(self, args=args)
  File "/opt/Empire/lib/common/modules.py", line 31, in __init__
    self.load_modules()
  File "/opt/Empire/lib/common/modules.py", line 61, in load_modules
    self.modules[moduleName] = imp.load_source(moduleName, filePath).Module(self.mainMenu, [])
  File "/opt/Empire//lib/modules/python/management/multi/socks.py", line 91
    options = {x.lower(): y for x, y in self.options.items()}

## Any additional information
i install every libary on centos .the  finally step ,ni occors "SyntaxError: invalid syntax"
,can anybody help me?
i try to change the python version to 2.7,but it occurs other errors:
[root@MyCloudServer Empire]# /usr/bin/python2.7 empire
[*] Loading stagers from: /opt/E/lib/stagers/
Traceback (most recent call last):
  File "empire", line 1365, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire/lib/common/empire.py", line 93, in __init__
    self.stagers = stagers.Stagers(self, args=args)
  File "/opt/Empire/lib/common/stagers.py", line 41, in __init__
    self.load_stagers()
  File "/opt/Empire/lib/common/stagers.py", line 54, in load_stagers
    for root, dirs, files in os.walk(rootPath):
  File "/usr/local/lib/python2.7/os.py", line 276, in walk
    names = listdir(top)
TypeError: must be encoded string without NULL bytes, not unicode

**Comment by utkusen** [comment]
I don't think centos is supported

**Comment by rvrsh3ll** [comment]
Sorry, OS not supported. Do a PR if you get it going :)
