### ISSUE TITLE
cant start empire latest version

### ISSUE THREAD

**Issue by dan7ez** [EmpireProject/Empire#882]
## Empire Version
2.3

## OS Information (Linux flavor, Python version)
kali

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

when i try to start empire i get this error

Traceback (most recent call last):
  File "./empire", line 13, in <module>
    from lib.common import empire, helpers
  File "/pentest/powershell/empire-ps/lib/common/empire.py", line 31, in <module>
    import agents
  File "/pentest/powershell/empire-ps/lib/common/agents.py", line 68, in <module>
    import encryption
  File "/pentest/powershell/empire-ps/lib/common/encryption.py", line 62, in <module>
    random_function = OpenSSL.rand.bytes
AttributeError: 'module' object has no attribute 'rand'

**Comment by killswitch-GUI** [comment]
You sure you properly installed? Also, did you read the error, it seems like your missing OpenSSL?

`random_function = OpenSSL.rand.bytes
AttributeError: 'module' object has no attribute 'rand'`

**Comment by killswitch-GUI** [comment]
This is a known issue and will be resolved soon.
