### ISSUE TITLE
error after last git pull

### ISSUE THREAD

**Issue by gnomefish** [EmpireProject/Empire#903]
Hey guys, 

I get this after doing a git pull (master branch) - Ubuntu 16.04

Traceback (most recent call last):
  File "./empire", line 1393, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire/lib/common/empire.py", line 103, in __init__
    self.listeners = listeners.Listeners(self, args=args)
  File "/opt/Empire/lib/common/listeners.py", line 35, in __init__
    self.load_listeners()
  File "/opt/Empire/lib/common/listeners.py", line 60, in load_listeners
    self.loadedListeners[listenerName] = imp.load_source(listenerName, filePath).Listener(self.mainMenu, [])
  File "/opt/Empire//lib/listeners/dbx.py", line 18, in <module>
    from lib.common import obfuscation
  File "/opt/Empire/lib/common/obfuscation.py", line 10, in <module>
    from pyminifier import token_utils as py_tokenizer
ImportError: No module named pyminifier

**Comment by DakotaNelson** [comment]
I believe running `setup.sh` should fix this - looks like you're missing
one of the dependencies added in the new version. You could also manually
install the dependencies using `pip` if you'd rather go that route.

**Comment by gnomefish** [comment]
yep, just removed it and reinstalled from scratch :)
saw some dependecies being added
thanks!

**Comment by KorayAgaya** [comment]
I have a same error

Traceback (most recent call last):
  File "./empire", line 1368, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/TOOLS/Empire/lib/common/empire.py", line 84, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable
