### ISSUE TITLE
Empire: listeners/dbx Dropbox Exception in thread Thread-1

### ISSUE THREAD

**Issue by gearcapitan** [EmpireProject/Empire#937]
## Empire Version
Last
## OS Information (Linux flavor, Python version)
KAli linux last

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/Empire/lib/common/helpers.py", line 892, in __run
    self.__run_backup()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/Empire//lib/listeners/dbx.py", line 839, in start_server
    dbx.users_get_current_account()
  File "/usr/local/lib/python2.7/dist-packages/dropbox/base.py", line 3277, in users_get_current_account
    None,
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 234, in request
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 325, in request_json_string_with_retry
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 409, in request_json_string
    timeout=timeout,
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 588, in urlopen
    timeout_obj = self._get_timeout(timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 303, in _get_timeout
    return Timeout.from_float(timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 154, in from_float
    return Timeout(read=timeout, connect=timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 94, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 127, in _validate_timeout
    "int, float or None." % (name, value))
ValueError: Timeout value connect was Timeout(connect=30, read=30, total=None), but it must be an int, float or None.

## Screenshot of error, embedded text output, or Pastebin link to the error

![kali linux-2018-01-16-23-04-15](https://user-images.githubusercontent.com/13740942/35026805-bc5b9c9a-fb12-11e7-8a43-ca2cf24cdcf2.png)

## Any additional information

I was eating a pancake

**Comment by xorrior** [comment]
@gearcapitan Can you update urllib3 and requests and try again?
pip install -U urllib3
pip install -U requests

**Comment by xorrior** [comment]
@gearcapitan I was able to test starting the dbx listener on kali rolling with Empire 2.4 . I didn't have any issues. Can you try starting the listener on a fresh install?

**Comment by xorrior** [comment]
Well, I spoke too soon. After 20 seconds or so, there was an exception because the connection was reset. Not the same error, but I don't think this is an issue with empire specifically. My 2nd thought would be to increase the DefaultDelay and PollInterval. As a side note, dropbox has released a new terms of service agreement. We got wind of changes that may be coming because of wide spread use of the dropbox listener. Additional testing needed for sure.

**Comment by xorrior** [comment]
@gearcapitan Ah, so after restarting the listener and increasing the PollInterval and DefaultDelay, the connection for the server was reset once again. Now I'm under the impression that Dropbox may be actively killing connections with the listener.

**Comment by gearcapitan** [comment]
I see, the truth is that I did not finish eating my pancake of the worried thing, in fact I left it aside and was testing other modules and for example in my case I detected that the module used to detect which antivirus has the agent, esque interrupts my connection after a while, and the truth gives me a lot of laziness to reinstall a new kali nothing more to prove the dropbox and this module, I think the truth if dropbox will give problems then remove that listener, since surely dropbox will feel like invaded or do not have a good image of empire, but anyway

**Comment by xorrior** [comment]
@gearcapitan I'll think about removing it. For now, I'll just add a disclaimer in the description.
