### ISSUE TITLE
Stack trace upon every agent connection

### ISSUE THREAD

**Issue by DanMcInerney** [EmpireProject/Empire#962]
## Empire Version
2.3.0

## OS Information (Linux flavor, Python version)
Kali Rolling 2017.3, 2.7.14+

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Every time an agent connects, a stack trace is thrown and the agent does not work as tested with the 'sysinfo' command. No job started message, no output.

## Screenshot of error, embedded text output, or Pastebin link to the error
(Empire) > [+] Initial agent Y57F3E1P from 10.2.0.99 now active (Slack)
[2018-01-30 22:53:52,521] ERROR in app: Exception on /login/process.php [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".../Empire//lib/listeners/http.py", line 1054, in handle_post
    encryptedAgent = encryption.aes_encrypt_then_hmac(sessionKey, agentCode)
  File ".../Empire/lib/common/encryption.py", line 141, in aes_encrypt_then_hmac
    data = aes_encrypt(key, data)
  File ".../Empire/lib/common/encryption.py", line 133, in aes_encrypt
    ct = encryptor.update(pad(data))+encryptor.finalize()
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 120, in update
    n = self.update_into(data, buf)
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 135, in update_into
    data, len(data))
TypeError: initializer for ctype 'unsigned char *' must be a str or list or tuple, not unicode
(Empire) > 

## Any additional information
This was all done on the http listener. Tried using both http and https stager URLs (Host option) but same error on both.

Empire 2.3.0 has a bunch of installation issues on Kali Rolling 2017.3 but I was able to solve all those and install without errors (other than missing libssl1.0.0 which I replaced with libssl1.0-dev) so I do not believe this issue is tied to any installation issues. See the other open issue on installation errors for my comment on how I solved those.

**Comment by DakotaNelson** [comment]
Looks like the error is in the listener.

Are you running this with Python 3? And is there any chance the agent is returning unicode data? It looks like unicode text is coming back from the agent when the listener expects a standard Python `str`. That could happen because Python 3 handles unicode differently.

**Comment by DanMcInerney** [comment]
Hmm, yes you're right. I'm running empire with python2 but a python3 script (deathstar) is creating the listener through the API. I just started empire outside the python3 virtualenv and without deathstar and no error. Will need to keep looking into this but appears to be my local environment rather than Empire issue.

**Comment by DakotaNelson** [comment]
So, to identify what you're running, you can use `python -V` or `which python`. Being in the virtualenv actually uses a different python binary - so having the virtualenv activated/deactivated does actually impact what version you're running.

You should be able to override what the virtualenv uses (I'm pretty sure... but not certain) by explicitly calling e.g. `python2 empire.py` or `/usr/bin/python empire.py`. That'll almost certainly break other virtualenv features, though.

This is fixable in code, but it would require a *ton* of careful string finagling/encoding/decoding and probably be an awful time.
