### ISSUE TITLE
Creating listener through API results in listener options being unicode strings instead of bytearrays leading to errors upon agent connection

### ISSUE THREAD

**Issue by DanMcInerney** [EmpireProject/Empire#965]
## Empire Version
2.3.0

## OS Information (Linux flavor, Python version)
Kali Rolling 2017.3, 2.7.14+

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
API calls to create the listener use unicode strings for all options set. These strings should be bytearrays as they are when you create a listener through the empire CLI.

## Screenshot of error, embedded text output, or Pastebin link to the error
Error when an agent connects to a listener that was created through the API with the Host option set:
(Empire: listeners/http) > 172.30.5.33 - - [01/Feb/2018 11:15:04] code 400, message Bad HTTP/0.9 request type ("\x16\x03\x01\x00Z\x01\x00\x00V\x03\x01ZsY'\x9cc\xd1\x97b\xb1.\x89\xfe*k\x06\xdbY\xc6\xad\x9c\xd2")
172.30.5.33 - - [01/Feb/2018 11:15:05] code 400, message Bad request syntax ("\x16\x03\x01\x00Z\x01\x00\x00V\x03\x01ZsY'\x03\xee\xc52s\xb9\x9eRk}r\xba@\x04\x84")

Error when an agent connects to a listener that was created through the API with both the Port and Host option set:
(Empire) > [+] Initial agent Y57F3E1P from 10.2.0.99 now active (Slack)
[2018-01-30 22:53:52,521] ERROR in app: Exception on /login/process.php [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".../Empire//lib/listeners/http.py", line 1054, in handle_post
    encryptedAgent = encryption.aes_encrypt_then_hmac(sessionKey, agentCode)
  File ".../Empire/lib/common/encryption.py", line 141, in aes_encrypt_then_hmac
    data = aes_encrypt(key, data)
  File ".../Empire/lib/common/encryption.py", line 133, in aes_encrypt
    ct = encryptor.update(pad(data))+encryptor.finalize()
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 120, in update
    n = self.update_into(data, buf)
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 135, in update_into
    data, len(data))
TypeError: initializer for ctype 'unsigned char *' must be a str or list or tuple, not unicode
(Empire) > 

## Any additional information
The way I found out that the API options are unicode strings was by sort of tricking Empire into telling me. 
-Create the listener through the API
-Kill the listener in Empire
-Run: uselistener http
-Run: launcher powershell

This will throw the following error if you created the listener through the API: [!] Error generating launcher: u'testing'
If you didn't create the listener through the API the error will look like so: [!] Error generating launcher: 'testing'

**Comment by DanMcInerney** [comment]
Little more info as I've been investigating. I added a line to empire.py line 725 to say:
values = values.encode('utf8')

While I don't get the _TypeError: initializer for ctype 'unsigned char *' must be a str or list or tuple, not unicode_ error anymore, I still get this error upon agent connection using _launcher powershell <listenername>_

_172.30.5.33 - - [01/Feb/2018 12:01:26] code 400, message Bad request syntax ('\x16\x03\x01\x00Z\x01\x00\x00V\x03\x01Zsd\x05\xcf\xa6\x90\xe8\x161fe\xbb\xb5\x9b\xd2\x91\xc3\x99\x15\x93m\xb2;\xc6*.r\x9ec#\x00\x00\x00\x0e\xc0')
172.30.5.33 - - [01/Feb/2018 12:01:26] code 400, message Bad request syntax ('\x16\x03\x01\x00Z\x01\x00\x00V\x03\x01Zsd\x05\x82@\xcc\xd3\xd6J\xa3\xc4\xa6\x19\\\xba>\x1a\xa3\x91~\xa2\x98)\xe0\xb6\x92X2\x81[P\x00\x00\x0e\xc0')'''_

**Comment by DanMcInerney** [comment]
Above bad request syntax was because I set host to https without a CertPath. So the original fix of adding ".encode('utf8')" is the solution and allows agents to connect successfully. Submitting PR shortly.
