### ISSUE TITLE
TypeError: 'type' object is not iterable

### ISSUE THREAD

**Issue by juliourena** [EmpireProject/Empire#999]
## Empire Version
Lastest

## OS Information (Linux flavor, Python version)
`Linux kali 4.14.0-kali3-amd64 #1 SMP Debian 4.14.13-1kali1 (2018-01-25) x86_64 GNU/Linux`
`Python 2.7.14+`
`Python 3.6.4
`
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
* I tried unistall pyopenssl and install it again 
* run multiple times ./setup/install.sh

While writing the report I notice that if I'm in /usr/lib/python2.7/dist-packages directory I can import OpenSSL but If I'm the Empire directory I can't 
```
root@kali:/usr/lib/python2.7/dist-packages# python
Python 2.7.14+ (default, Feb  6 2018, 19:12:18) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from OpenSSL import SSL
>>> 

root@kali:~/prog/Empire# python
Python 2.7.14+ (default, Feb  6 2018, 19:12:18) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/dist-packages/seccure-0.3.3.dev0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/wafw00f-0.9.4-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/pluginbase-0.3-py2.7.egg', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/wx-3.0-gtk2']
>>> import OpenSSL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/extensions.py", line 24, in <module>
    from cryptography.x509.general_name import GeneralName, IPAddress, OtherName
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/general_name.py", line 18, in <module>
    from cryptography.x509.name import Name
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/name.py", line 28, in <module>
    _ASN1_TYPE_TO_ENUM = dict((i.value, i) for i in _ASN1Type)
TypeError: 'type' object is not iterable
```

## Screenshot of error, embedded text output, or Pastebin link to the error
```
root@kali:~/prog/Empire# ./empire 
Traceback (most recent call last):
  File "./empire", line 8, in <module>
    from OpenSSL import SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/extensions.py", line 24, in <module>
    from cryptography.x509.general_name import GeneralName, IPAddress, OtherName
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/general_name.py", line 18, in <module>
    from cryptography.x509.name import Name
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/name.py", line 28, in <module>
    _ASN1_TYPE_TO_ENUM = dict((i.value, i) for i in _ASN1Type)
TypeError: 'type' object is not iterable
```

## Any additional information
```
root@kali:~/prog/Empire# openssl version
OpenSSL 1.1.0g  2 Nov 2017

root@kali:~/prog/Empire# dpkg -l |grep openssl
ii  libevent-openssl-2.1-6:amd64                                     2.1.8-stable-4                       amd64        Asynchronous event notification library (openssl)
ii  libgnutls-openssl27:amd64                                        3.5.17-1                             amd64        GNU TLS library - OpenSSL wrapper
ii  libxmlsec1-openssl:amd64                                         1.2.25-1                             amd64        Openssl engine for the XML security library
ii  openssl                                                          1.1.0g-2                             amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  perl-openssl-defaults:amd64                                      3                                    amd64        version compatibility baseline for Perl OpenSSL packages
ii  python-openssl                                                   17.5.0-1                             all          Python 2 wrapper around the OpenSSL library
ii  python3-openssl                                                  17.5.0-1                             all          Python 3 wrapper around the OpenSSL library
```

**Comment by xorrior** [comment]
@juliourena Did you see any error messages during the install? Also, what version of python is used with Empire?

**Comment by juliourena** [comment]
Same error during installation. For Empire I'm using python 2.7.14+

Note: if I drop all empire files into `/usr/lib/python2.7/dist-package/` empire will run. But not outsite this directory

**Comment by i0nsec** [comment]
@juliourena Have you tried to run the reset script located in `Empire/setup/reset.sh`
I ran into the same issue and was able to solve it by executing the reset script.

**Comment by juliourena** [comment]
Hi @i0nsec same issue 

```
root@kali:~/prog/Empire# ./setup/reset.sh 

 [>] Enter server negotiation password, enter for random generation: 

 [*] Database setup completed!

Traceback (most recent call last):
  File "./empire", line 8, in <module>
    from OpenSSL import SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/extensions.py", line 24, in <module>
    from cryptography.x509.general_name import GeneralName, IPAddress, OtherName
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/general_name.py", line 18, in <module>
    from cryptography.x509.name import Name
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/name.py", line 28, in <module>
    _ASN1_TYPE_TO_ENUM = dict((i.value, i) for i in _ASN1Type)
TypeError: 'type' object is not iterable
```

**Comment by xorrior** [comment]
@juliourena Can you try updating the cryptography package (pip install -U cryptography) ?

**Comment by DakotaNelson** [comment]
This also looks similar to things I've seen when `openssl` isn't installed or is just generally being a pain... which it usually is. That might also be worth checking.

In addition, following the advice in [this issue](https://github.com/pyca/cryptography/issues/4020) might help.

**Comment by juliourena** [comment]
Looks like @DakotaNelson instructions works

Thanks Bro! 

```
pip uninstall enum
pip install enum34

can fixed this bug
```

**Comment by DakotaNelson** [comment]
Glad it helped!

**Comment by tongpinmo** [comment]
@juliourena hello when i run  
`pip uninstall enum`
the error is listed as below:
  File "/usr/local/lib/python2.7/dist-packages/cryptography/x509/name.py", line 28, in <module>
    _ASN1_TYPE_TO_ENUM = dict((i.value, i) for i in _ASN1Type)
TypeError: 'type' object is not iterable

pip seems to be useless

**Comment by DakotaNelson** [comment]
Hm, yeah, looks like you pointed it out to the folks running the library as well: https://github.com/pyca/cryptography/issues/4020

Honestly I'm not sure there's much Empire can do about this, probably just need to keep an eye on that thread for a fix.
